#version 430 core
layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// 粒子の物理量
struct Particle
{
  // 位置
  vec4 position;

  // 速度
  vec3 velocity;

  // 力
  vec3 force;
};

// 粒子群データ
layout(std430, binding = 0) buffer Particles
{
  Particle particle[];
};

void main()
{
  // ワークグループ ID をそのまま粒子データのインデックスに使う
  const uint i = gl_WorkGroupID.x;

  // 粒子の力を初期化
  particle[i].force = vec3(0.0, 0.0, 0.0);
}
